# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11iAUsm9C81yACv5lVhnwAVLO2MdbzlZ4
"""

import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

# Menggunakan Keras langsung melalui TensorFlow
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, Dense, Dropout, Flatten
from tensorflow.keras.utils import to_categorical
import pickle

# ==========================================
# 1. MEMUAT DATASET ASLI (.XLSX)
# ==========================================
file_name = "Data_Bayam_Brazil_1440_Periode_Jan - Feb.xlsx"
df = pd.read_excel(file_name, skiprows=2, engine="openpyxl")
df.columns = df.columns.str.strip()

# Konversi kolom Kelembapan ke persen (0-100%) jika di Excel berupa desimal (0.73 -> 73%)
if df["Kelembapan(%)"].max() <= 1.0:
    df["Kelembapan(%)"] = df["Kelembapan(%)"] * 100

print(f"Berhasil memuat {len(df)} baris data asli untuk Bayam Brazil.\n")

# ==========================================
# 2. PREPROCESSING DATA
# ==========================================
X = df[["Kelembapan(%)", "Suhu (°C)"]].values
y = df["Status Tanah"].values

# Encode Target Label (Kering, Normal, Basah)
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)
num_classes = len(np.unique(y_encoded))
y_categorical = to_categorical(y_encoded, num_classes=num_classes)

# Standardisasi Fitur (Sangat penting agar hasil prediksi di web nanti konsisten)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Simpan objek Scaler dan LabelEncoder agar bisa dipakai kembali di script Web Anda
with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)
with open("label_encoder.pkl", "wb") as f:
    pickle.dump(label_encoder, f)
print("-> Scaler dan LabelEncoder berhasil disimpan (scaler.pkl & label_encoder.pkl)")

# Reshape data untuk 1D CNN: [samples, time_steps, features]
X_cnn = X_scaled.reshape(X_scaled.shape[0], 1, X_scaled.shape[1])

# Split data (80% Train, 20% Test)
X_train, X_test, y_train, y_test = train_test_split(
    X_cnn, y_categorical, test_size=0.2, random_state=42, stratify=y_encoded
)

# ==========================================
# 3. MEMBANGUN ARSITEKTUR KEROS 1D CNN
# ==========================================
model = Sequential([
    # Layer Konvolusi 1D Keras
    Conv1D(filters=32, kernel_size=1, activation="relu", input_shape=(X_train.shape[1], X_train.shape[2])),
    Dropout(0.2),

    Conv1D(filters=64, kernel_size=1, activation="relu"),
    Dropout(0.2),

    Flatten(),
    Dense(64, activation="relu"),
    Dropout(0.3),

    # Output Layer menggunakan Softmax
    Dense(num_classes, activation="softmax")
])

# Kompilasi Model Keras
model.compile(
    optimizer="adam",
    loss="categorical_crossentropy",
    metrics=["accuracy"]
)

model.summary()

# ==========================================
# 4. TRAINING MODEL KEROS
# ==========================================
print("\n--- Memulai Proses Training Model Keras ---")
history = model.fit(
    X_train, y_train,
    epochs=25,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)
print("Training selesai!")

# ==========================================
# 5. MENYIMPAN MODEL (.H5) UNTUK IMPLEMENTASI WEB
# ==========================================
model_path = "model_bayam_brazil.h5"
model.save(model_path)
print(f"\n-> MODEL KERAS BERHASIL DISIMPAN: '{model_path}'")
print("File ini yang akan dimasukkan ke dalam folder project web Anda.\n")

# ==========================================
# 6. VISUALISASI GRAFIK PENYIRAMAN
# ==========================================
sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(1, 2, figsize=(15, 5))

# Grafik Sebaran Sensor & Batas Aturan Penyiraman
warna_status = {"Basah": "blue", "Normal": "green", "Kering": "red"}
sns.scatterplot(data=df, x="Kelembapan(%)", y="Suhu (°C)", hue="Status Tanah", palette=warna_status, alpha=0.7, ax=axes[0])
axes[0].axvline(40, color="orange", linestyle="--", label="Batas Kering (<40%)")
axes[0].axvline(70, color="purple", linestyle="--", label="Batas Basah (>70%)")
axes[0].set_title("Visualisasi Threshold Batas Penyiraman")
axes[0].set_xlabel("Kelembapan Tanah (%)")
axes[0].set_ylabel("Suhu (°C)")
axes[0].legend()

# Grafik Akurasi Model Keras
axes[1].plot(history.history["accuracy"], label="Train Accuracy", color="blue")
axes[1].plot(history.history["val_accuracy"], label="Val Accuracy", color="orange")
axes[1].set_title("Grafik Akurasi Pembelajaran Keras")
axes[1].set_xlabel("Epoch")
axes[1].set_ylabel("Akurasi")
axes[1].legend()

plt.tight_layout()
plt.show()